imports:
    - { resource: twitter.conf.yml }

parameters:
    letgo.twitter.reader.class: Letgo\TwitterBundle\Services\Twitter\Reader
    guzzle.oauth.class: GuzzleHttp\Subscriber\Oauth\Oauth1

services:
    letgo.twitter.reader:
        class: "%letgo.twitter.reader.class%"
        arguments:
            oauth: "@guzzle.oauth"
            base_url: "%twitter.base_url%"
    guzzle.oauth:
        class: "%guzzle.oauth.class%"
        arguments: ["%twitter.config%"]