imports:
    - { resource: twitter.conf.yml }

parameters:
    letgo.twitter.reader.class: Letgo\TwitterBundle\Services\Twitter\Reader
    guzzle.oauth.class: GuzzleHttp\Subscriber\Oauth\Oauth1
    guzzle.stack.class: GuzzleHttp\HandlerStack
    guzzle.client.class: GuzzleHttp\Client

services:
    guzzle.client:
        class: "%guzzle.client.class%"
        arguments: - {base_uri: "%twitter.base_uri%", auth: 'oauth', handler: "@guzzle.stack"}
    guzzle.stack:
        class: "%guzzle.stack.class%"
        factory: ["%guzzle.stack.class%", create]
        calls:
            - [push, ["@guzzle.oauth"]]
    guzzle.oauth:
        class: "%guzzle.oauth.class%"
        arguments: ["%twitter.config%"]
    letgo.twitter.reader:
        class: "%letgo.twitter.reader.class%"
        arguments:
            twitter_client: "@guzzle.client"