parameters:
    twitter.base_url: "https://api.twitter.com/1.1"
    twitter.config:
        consumer_key: "Ct67CMSMLMygbIO07np38U4KV"
        consumer_secret: "Ft4CS5tE0VLQ3OiHWSlaABQeADsslVRywBUghdelT4mw2hwPq4"
        token: "728145508351385600-hkiOhSoBkrDBimUMhfCN6vSu6EzUJth"
        token_secret: "F2oxc0DoT9Va02Vq6fevENKZLBzk50tk9dlvaX71xOFnc"
